# -*- coding: utf-8 -*-

"""
/***************************************************************************
 DiversityProcessing
                                 A QGIS plugin
 Calculates several commn indecis of diversity
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-02-09
        copyright            : (C) 2021 by GeoDigit d.o.o.
        email                : nedic.darko@geodigit.rs
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'GeoDigit d.o.o.'
__date__ = '2021-02-09'
__copyright__ = '(C) 2021 by GeoDigit d.o.o.'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterField,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingOutputString)

from .diversity_functions import *


class DiversityProcessingAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    # OUTPUT = 'OUTPUT'
    # INPUT = 'INPUT'

    # INPUTS AND OUTPUTS
    POLYLAYER = "POLYLAYER"
    CATEGORYFIELD = "CATEGORYFIELD"
    POINTLAYER = "POINTLAYER"
    SPECIESFIELD = "SPECIESFIELD"
    SUMMARY_DICTIONARY = "SUMMARY DICTIONARY"
    SUMMARY_HTML = "SUMMARY_HTML"

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.POLYLAYER,
                self.tr('Polygon layer'),
                [QgsProcessing.TypeVectorAnyGeometry]
            )
        )

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterField(
                self.CATEGORYFIELD,
                self.tr('Category layer'),
                None,
                self.POLYLAYER,
                QgsProcessingParameterField.String
            )
        )

        # add point layer Input/Output
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.POINTLAYER,
                self.tr('Point layer'),
                [QgsProcessing.TypeVectorPoint]
            )
        )

        self.addParameter(
            QgsProcessingParameterField(
                self.SPECIESFIELD,
                self.tr('Species fields'),
                None,
                self.POINTLAYER,
                QgsProcessingParameterField.String
            )
        )

        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.SUMMARY_HTML,
                self.tr('Output HTML File'),
                'HTML Files *.html',
            )
        )

        self.addOutput(
            QgsProcessingOutputString(
                self.SUMMARY_DICTIONARY,
                self.tr("Results (string)")
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        lyrPoly = self.parameterAsSource(parameters, self.POLYLAYER, context)
        lyrPoint = self.parameterAsSource(parameters, self.POINTLAYER, context)

        fldCategory = self.parameterAsString(
            parameters, self.CATEGORYFIELD, context)
        fldCpecies = self.parameterAsString(
            parameters, self.SPECIESFIELD, context)

        outFile = self.parameterAsFileOutput(parameters, self.SUMMARY_HTML, context)

        dctMain = {}
        # loop thru all polygon layer selected in combo box
        for poly in lyrPoly.getFeatures():
            if feedback.isCanceled():
                feedback.pushInfo("Canceled by user")
                break

            sCategory = poly.attribute(fldCategory)
            feedback.pushInfo("Category: {}".format(sCategory))
            # QgsMessageLog.logMessage("Category: {}".format(
            # sCategory), "Diversity Calculator", level=Qgis.Info)
            dctSummary = dc_summarizePoly(poly, lyrPoint, fldCpecies)
            feedback.pushDebugInfo("Summary: {}".format(dctSummary))
            # QgsMessageLog.logMessage("Summary: {}".format(
            # dctSummary), "Diversity Calculator", level=Qgis.Info)

            dctMain = dc_MergeDictionaries(dctMain, sCategory, dctSummary)

        feedback.pushInfo(str(dctMain))

        return {self.SUMMARY_DICTIONARY: str(dctMain), self.SUMMARY_HTML: outFile }
        # (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
        #                                        context, source.fields(), source.wkbType(), source.sourceCrs())

        # # Compute the number of steps to display within the progress bar and
        # # get features from source
        # total = 100.0 / source.featureCount() if source.featureCount() else 0
        # features = source.getFeatures()

        # for current, feature in enumerate(features):
        #     # Stop the algorithm if cancel button has been clicked
        #     if feedback.isCanceled():
        #         break

        #     # Add a feature in the sink
        #     sink.addFeature(feature, QgsFeatureSink.FastInsert)

        #     # Update the progress bar
        #     feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        # return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Diversity Calculator'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Diversity'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return DiversityProcessingAlgorithm()

    # create help
    def helpUrl(self):
        return "https://geodigit.rs"

    def shortHelpString(self):
        str = """
        Calculate common indices of deversity for a set of polygons from a set of point observations of species.

        Richness, Ebenness, Shannons diversity index, and simpsons's diversity index are calculated for each polygon or a group of polygons that have the same something.

        The points file is required to have the same name of the species as an attribute for point.
        """
        return str

    def shortDescription(self):
        return "Calculates common indices of species diversity"

    def icon(self):
        return QIcon("icon.png")
